### ISSUE TITLE
There should be API Path to Get Data in JSON Format

### ISSUE THREAD

**Issue by arunpc4u** [jcvignoli/lumiere-movies#42]
There should be a Path (wordpress.com/lumirer-movies/v1/api/movies/tmdbid), where we can see imdb movie/tv-movie/tv-shows in json data format!

### Why We Should need this?
Doing this will be Great so that we Anyone (Wordpress admin only) can easily get Data manually from JSON DATA (API URL) also it will helpful in many terms! <3

If you are not interested in this, can you please let me know is there any function with that directly we can get data in json/array format!?

**Comment by jcvignoli** [comment]
Hi @arunpc4u 

I'm not sure I understand your request: what would be the purpose of creating an api that would show the data retrieved?

There is no class/method/function that makes json files. I guess it would be doable, for example by parsing the HTML pages saved from IMDb website and then creating an additional cache made of json files.

For the records, the wordpress plugin Lumière uses a [fork](https://github.com/jcvignoli/imdbphp) fo [IMDbPHP library](https://github.com/tboothman/imdbphp) which uses a graphql library to retrieve information from [IMDb website](https://www.imdb.com/).

**Comment by jcvignoli** [comment]
closing the issue, seems like a random request on git.
