### ISSUE TITLE
Option settings on the general options page don't keep. 

### ISSUE THREAD

**Issue by tomandersen** [jcvignoli/lumiere-movies#44]
EG change from 'grey' to 'white' , then update settings, its back to 'grey'

Other settings work like 'Data Management' 

Note - our theme 'hello elementor' has no widgets (which is fine for us, i am not using widgets).

<img width="1001" alt="Screenshot 2024-11-13 at 3 32 20 PM" src="https://github.com/user-attachments/assets/5732399e-293a-4449-b9ab-ad5cec2221ee">

**Comment by jcvignoli** [comment]
Hi @tomandersen 

Thanks for letting me know. Actually, I found the bug a couple of days ago. Since I'm introducing a couple of changes, I'm debugging the plugin right now.

The new release will adress this bug and will be published very soon.

Thanks for your kind words!

**Comment by jcvignoli** [comment]
fixed in latest release 4.2.1.
Thanks for taking the time of reporting the bug @tomandersen

**Comment by tomandersen** [comment]
Thanks for the fast fix! (i left a review on Wordpress too)

**Comment by tomandersen** [comment]
I got 4.2.1 and the options saving did not work! I was on another task, and noticed that my site (a new one) was still on the 40MB limit of wordpress, (oh no!) I set it higher and now the options work.

**Comment by jcvignoli** [comment]
I'm so glad you can use the plugin. I also thank you for your very nice review ;)
